### ISSUE TITLE
Captura en Debian

### ISSUE THREAD

**Issue by osckarsevilla** [william89731/image-registry-updater#2]
![imagen](https://github.com/william89731/image-registry-updater/assets/55624987/dd7ea41e-8ae2-42c8-aaa7-8ecb2b584f34)

**Comment by william89731** [comment]
es necesario: 
- el report en un paste.
- el formato de las imagenes DEBEN ser  "owner:repo:tag"  (ejemplo tag 1.2.2)
-  lista imagenes (docker images --format "{{.Repository}}:{{.Tag}})
