### ISSUE TITLE
Archlinux sobre LCX Proxmox

### ISSUE THREAD

**Issue by osckarsevilla** [william89731/image-registry-updater#3]
#archlinux1 Imagenes corriendo

![imagen](https://github.com/william89731/image-registry-updater/assets/55624987/bca12e5f-982e-4896-82e4-8f19d736a5f9)

#archlinux2 comando corriendo

![imagen](https://github.com/william89731/image-registry-updater/assets/55624987/e3853b8c-8fac-4d55-b8ea-1a40d7e0ce93)

**Comment by william89731** [comment]
tienes un monton de images con el tag "latest". es una muy mala practica :/ (ya sabes, en un momento y se puede romper el servicio) 

el tool no va a funcionar. gracias por tu ayuda :)
